name: pyTSEB
channels:
    - conda-forge
dependencies:
    - python=3
    - gdal
    - numpy
    - matplotlib
    - scipy
    - pandas
    - jupyter
    - notebook
    - bokeh
    - netCDF4
    - pip
    - pip:
        - git+https://github.com/BenjMy/pyTSEB
        - git+https://github.com/hectornieto/pypro4sail
