name: EOMAJI
channels:
    - conda-forge
dependencies:
    - python=3.9
    - spyder<6.0.0
    - numpy
    - matplotlib
    - scipy
    - pandas
    - notebook
    - xarray
    - rioxarray
    - geopandas
    - shapely
    - contextily
    - pip
      - cdsapi
      - cftime